<a href="https://colab.research.google.com/github/alstj003/2025-1-A-myclass-BDA/blob/main/inclass/06w_A_mon_0414_easy_ch06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 단원 06-05 파생변수 추가

In [1]:
!git clone http://github.com/ai7dnn/data

Cloning into 'data'...
warning: redirecting to https://github.com/ai7dnn/data/
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 24 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (24/24), 2.14 MiB | 3.68 MiB/s, done.
Resolving deltas: 100% (4/4), done.

In [2]:
import pandas as pd
import numpy as np

exam = pd.read_csv('data/exam.csv')
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [5]:
exam.assign(total = exam['math'] + exam['english'] + exam['science'])
exam.head(3)

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78

In [6]:
exam.assign(total = exam['math'] + exam['english'] + exam['science'],
            mean = (exam['math'] + exam['english'] + exam['science']) / 3)

    id  nclass  math  english  science  total       mean
0    1       1    50       98       50    198  66.000000
1    2       1    60       97       60    217  72.333333
2    3       1    45       86       78    209  69.666667
3    4       1    30       98       58    186  62.000000
4    5       2    25       80       65    170  56.666667
5    6       2    50       89       98    237  79.000000
6    7       2    80       90       45    215  71.666667
7    8       2    90       78       25    193  64.333333
8    9       3    20       98       15    133  44.333333
9   10       3    50       98       45    193  64.333333
10  11       3    65       65       65    195  65.000000
11  12       3    45       85       32    162  54.000000
12  13       4    46       98       65    209  69.666667
13  14       4    48       87       12    147  49.000000
14  15       4    75       56       78    209  69.666667
15  16       4    58       98       65    221  73.666667
16  17       5    65       68       98    231  77.000000
17  18       5    80       78       90    248  82.666667
18  19       5    89       68       87    244  81.333333
19  20       5    78       83       58    219  73.000000

In [7]:
exam.assign(test = np.where(exam.science >= 60, 'pass', 'fail'))

    id  nclass  math  english  science  test
0    1       1    50       98       50  fail
1    2       1    60       97       60  pass
2    3       1    45       86       78  pass
3    4       1    30       98       58  fail
4    5       2    25       80       65  pass
5    6       2    50       89       98  pass
6    7       2    80       90       45  fail
7    8       2    90       78       25  fail
8    9       3    20       98       15  fail
9   10       3    50       98       45  fail
10  11       3    65       65       65  pass
11  12       3    45       85       32  fail
12  13       4    46       98       65  pass
13  14       4    48       87       12  fail
14  15       4    75       56       78  pass
15  16       4    58       98       65  pass
16  17       5    65       68       98  pass
17  18       5    80       78       90  pass
18  19       5    89       68       87  pass
19  20       5    78       83       58  fail

In [10]:
exam = pd.read_csv('data/exam.csv')
exam.sample(frac=.3)

    id  nclass  math  english  science
6    7       2    80       90       45
0    1       1    50       98       50
5    6       2    50       89       98
12  13       4    46       98       65
7    8       2    90       78       25
1    2       1    60       97       60

In [11]:
exam.assign(total = exam.math + exam.english + exam.science)

    id  nclass  math  english  science  total
0    1       1    50       98       50    198
1    2       1    60       97       60    217
2    3       1    45       86       78    209
3    4       1    30       98       58    186
4    5       2    25       80       65    170
5    6       2    50       89       98    237
6    7       2    80       90       45    215
7    8       2    90       78       25    193
8    9       3    20       98       15    133
9   10       3    50       98       45    193
10  11       3    65       65       65    195
11  12       3    45       85       32    162
12  13       4    46       98       65    209
13  14       4    48       87       12    147
14  15       4    75       56       78    209
15  16       4    58       98       65    221
16  17       5    65       68       98    231
17  18       5    80       78       90    248
18  19       5    89       68       87    244
19  20       5    78       83       58    219

In [12]:
exam.assign(total = exam.math + exam.english + exam.science).sort_values('total')

    id  nclass  math  english  science  total
8    9       3    20       98       15    133
13  14       4    48       87       12    147
11  12       3    45       85       32    162
4    5       2    25       80       65    170
3    4       1    30       98       58    186
9   10       3    50       98       45    193
7    8       2    90       78       25    193
10  11       3    65       65       65    195
0    1       1    50       98       50    198
12  13       4    46       98       65    209
14  15       4    75       56       78    209
2    3       1    45       86       78    209
6    7       2    80       90       45    215
1    2       1    60       97       60    217
19  20       5    78       83       58    219
15  16       4    58       98       65    221
16  17       5    65       68       98    231
5    6       2    50       89       98    237
18  19       5    89       68       87    244
17  18       5    80       78       90    248

In [13]:
exam.assign(total = exam.math + exam.english + exam.science).sort_values('total', ascending=False)

    id  nclass  math  english  science  total
17  18       5    80       78       90    248
18  19       5    89       68       87    244
5    6       2    50       89       98    237
16  17       5    65       68       98    231
15  16       4    58       98       65    221
19  20       5    78       83       58    219
1    2       1    60       97       60    217
6    7       2    80       90       45    215
14  15       4    75       56       78    209
12  13       4    46       98       65    209
2    3       1    45       86       78    209
0    1       1    50       98       50    198
10  11       3    65       65       65    195
7    8       2    90       78       25    193
9   10       3    50       98       45    193
3    4       1    30       98       58    186
4    5       2    25       80       65    170
11  12       3    45       85       32    162
13  14       4    48       87       12    147
8    9       3    20       98       15    133

In [21]:
exam.assign(total = exam.math + exam.english + exam.science,
            mean = lambda x: x.total / 3)

    id  nclass  math  english  science  total       mean
0    1       1    50       98       50    198  66.000000
1    2       1    60       97       60    217  72.333333
2    3       1    45       86       78    209  69.666667
3    4       1    30       98       58    186  62.000000
4    5       2    25       80       65    170  56.666667
5    6       2    50       89       98    237  79.000000
6    7       2    80       90       45    215  71.666667
7    8       2    90       78       25    193  64.333333
8    9       3    20       98       15    133  44.333333
9   10       3    50       98       45    193  64.333333
10  11       3    65       65       65    195  65.000000
11  12       3    45       85       32    162  54.000000
12  13       4    46       98       65    209  69.666667
13  14       4    48       87       12    147  49.000000
14  15       4    75       56       78    209  69.666667
15  16       4    58       98       65    221  73.666667
16  17       5    65       68       98    231  77.000000
17  18       5    80       78       90    248  82.666667
18  19       5    89       68       87    244  81.333333
19  20       5    78       83       58    219  73.000000

In [16]:
# 람다 함수
(lambda x, y: x + y)(15, 30)

45

In [17]:
f = lambda x, y: x + y
f(15, 30)

45

In [20]:
round(3.8976, 3)

3.898

In [23]:
exam.assign(total = exam.math + exam.english + exam.science,
            mean = lambda x: round(x.total / 3, 2))

    id  nclass  math  english  science  total   mean
0    1       1    50       98       50    198  66.00
1    2       1    60       97       60    217  72.33
2    3       1    45       86       78    209  69.67
3    4       1    30       98       58    186  62.00
4    5       2    25       80       65    170  56.67
5    6       2    50       89       98    237  79.00
6    7       2    80       90       45    215  71.67
7    8       2    90       78       25    193  64.33
8    9       3    20       98       15    133  44.33
9   10       3    50       98       45    193  64.33
10  11       3    65       65       65    195  65.00
11  12       3    45       85       32    162  54.00
12  13       4    46       98       65    209  69.67
13  14       4    48       87       12    147  49.00
14  15       4    75       56       78    209  69.67
15  16       4    58       98       65    221  73.67
16  17       5    65       68       98    231  77.00
17  18       5    80       78       90    248  82.67
18  19       5    89       68       87    244  81.33
19  20       5    78       83       58    219  73.00

In [24]:
pd.set_option('display.precision', 2)

In [25]:
exam.assign(total = exam.math + exam.english + exam.science,
            mean = lambda x: x.total / 3)

    id  nclass  math  english  science  total   mean
0    1       1    50       98       50    198  66.00
1    2       1    60       97       60    217  72.33
2    3       1    45       86       78    209  69.67
3    4       1    30       98       58    186  62.00
4    5       2    25       80       65    170  56.67
5    6       2    50       89       98    237  79.00
6    7       2    80       90       45    215  71.67
7    8       2    90       78       25    193  64.33
8    9       3    20       98       15    133  44.33
9   10       3    50       98       45    193  64.33
10  11       3    65       65       65    195  65.00
11  12       3    45       85       32    162  54.00
12  13       4    46       98       65    209  69.67
13  14       4    48       87       12    147  49.00
14  15       4    75       56       78    209  69.67
15  16       4    58       98       65    221  73.67
16  17       5    65       68       98    231  77.00
17  18       5    80       78       90    248  82.67
18  19       5    89       68       87    244  81.33
19  20       5    78       83       58    219  73.00

In [26]:
exam.assign(total = lambda d: d.math + d.english + d.science,
            mean = lambda x: x.total / 3)

    id  nclass  math  english  science  total   mean
0    1       1    50       98       50    198  66.00
1    2       1    60       97       60    217  72.33
2    3       1    45       86       78    209  69.67
3    4       1    30       98       58    186  62.00
4    5       2    25       80       65    170  56.67
5    6       2    50       89       98    237  79.00
6    7       2    80       90       45    215  71.67
7    8       2    90       78       25    193  64.33
8    9       3    20       98       15    133  44.33
9   10       3    50       98       45    193  64.33
10  11       3    65       65       65    195  65.00
11  12       3    45       85       32    162  54.00
12  13       4    46       98       65    209  69.67
13  14       4    48       87       12    147  49.00
14  15       4    75       56       78    209  69.67
15  16       4    58       98       65    221  73.67
16  17       5    65       68       98    231  77.00
17  18       5    80       78       90    248  82.67
18  19       5    89       68       87    244  81.33
19  20       5    78       83       58    219  73.00

## df.agg() : 다양한 집계 연산을 수행

In [27]:
exam = pd.read_csv('data/exam.csv')
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [28]:
exam.agg("mean")

id         10.50
nclass      3.00
math       57.45
english    84.90
science    59.45
dtype: float64

In [29]:
exam.mean()

id         10.50
nclass      3.00
math       57.45
english    84.90
science    59.45
dtype: float64

In [30]:
exam.agg(["mean", 'max', 'min', 'median'])

          id  nclass   math  english  science
mean    10.5     3.0  57.45     84.9    59.45
max     20.0     5.0  90.00     98.0    98.00
min      1.0     1.0  20.00     56.0    12.00
median  10.5     3.0  54.00     86.5    62.50

In [31]:
exam.describe()

          id  nclass   math  english  science
count  20.00   20.00  20.00    20.00    20.00
mean   10.50    3.00  57.45    84.90    59.45
std     5.92    1.45  20.30    12.88    25.29
min     1.00    1.00  20.00    56.00    12.00
25%     5.75    2.00  45.75    78.00    45.00
50%    10.50    3.00  54.00    86.50    62.50
75%    15.25    4.00  75.75    98.00    78.00
max    20.00    5.00  90.00    98.00    98.00

In [32]:
exam.agg(mean_math = ("math", "mean"))

            math
mean_math  57.45

In [35]:
exam.agg(["mean", "median"], axis=1)

    mean  median
0   40.0    50.0
1   44.0    60.0
2   42.6    45.0
3   38.2    30.0
4   35.4    25.0
5   49.0    50.0
6   44.8    45.0
7   40.6    25.0
8   29.0    15.0
9   41.2    45.0
10  41.8    65.0
11  35.4    32.0
12  45.2    46.0
13  33.0    14.0
14  45.6    56.0
15  48.2    58.0
16  50.6    65.0
17  54.2    78.0
18  53.6    68.0
19  48.8    58.0

In [37]:
import numpy as np

df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, 10]],
                   columns=['A', 'B', 'C'])
df

     A    B   C
0  1.0  2.0   3
1  4.0  5.0   6
2  7.0  8.0   9
3  NaN  NaN  10

In [38]:
import numpy as np

df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, None, 10]],
                   columns=['A', 'B', 'C'])
df

     A    B   C
0  1.0  2.0   3
1  4.0  5.0   6
2  7.0  8.0   9
3  NaN  NaN  10

In [39]:
df.agg(["sum", 'mean', 'median', 'min', 'max', 'count'])

           A     B     C
sum     12.0  15.0  28.0
mean     4.0   5.0   7.0
median   4.0   5.0   7.5
min      1.0   2.0   3.0
max      7.0   8.0  10.0
count    3.0   3.0   4.0

In [40]:
df.agg(['sum', 'mean', 'median', 'min', 'max', 'count'], axis=0)

           A     B     C
sum     12.0  15.0  28.0
mean     4.0   5.0   7.0
median   4.0   5.0   7.5
min      1.0   2.0   3.0
max      7.0   8.0  10.0
count    3.0   3.0   4.0

In [41]:
df.agg(['sum', 'mean', 'median', 'min', 'max', 'count'], axis='index')

           A     B     C
sum     12.0  15.0  28.0
mean     4.0   5.0   7.0
median   4.0   5.0   7.5
min      1.0   2.0   3.0
max      7.0   8.0  10.0
count    3.0   3.0   4.0

In [42]:
df.agg(['sum', 'mean', 'median', 'min', 'max', 'count'], axis=1)

    sum  mean  median   min   max  count
0   6.0   2.0     2.0   1.0   3.0    3.0
1  15.0   5.0     5.0   4.0   6.0    3.0
2  24.0   8.0     8.0   7.0   9.0    3.0
3  10.0  10.0    10.0  10.0  10.0    1.0

In [43]:
df.agg(['sum', 'mean', 'median', 'min', 'max', 'count'], axis='columns')

    sum  mean  median   min   max  count
0   6.0   2.0     2.0   1.0   3.0    3.0
1  15.0   5.0     5.0   4.0   6.0    3.0
2  24.0   8.0     8.0   7.0   9.0    3.0
3  10.0  10.0    10.0  10.0  10.0    1.0

In [44]:
exam.groupby('nclass').agg(mean_math = ("math", "mean"))

        mean_math
nclass
1           46.25
2           61.25
3           45.00
4           56.75
5           78.00

In [45]:
exam.groupby('nclass').agg(max_math = ("math", "max"))

        max_math
nclass
1             60
2             90
3             65
4             75
5             89

In [46]:
exam.groupby('nclass').mean()

          id   math  english  science
nclass
1        2.5  46.25    94.75    61.50
2        6.5  61.25    84.25    58.25
3       10.5  45.00    86.50    39.25
4       14.5  56.75    84.75    55.00
5       18.5  78.00    74.25    83.25

In [47]:
exam.groupby('nclass').agg('mean')

          id   math  english  science
nclass
1        2.5  46.25    94.75    61.50
2        6.5  61.25    84.25    58.25
3       10.5  45.00    86.50    39.25
4       14.5  56.75    84.75    55.00
5       18.5  78.00    74.25    83.25

In [48]:
exam.groupby('nclass').mean()[["math"]]

         math
nclass
1       46.25
2       61.25
3       45.00
4       56.75
5       78.00

In [49]:
exam.groupby('nclass').mean()[["math", 'science']]

         math  science
nclass
1       46.25    61.50
2       61.25    58.25
3       45.00    39.25
4       56.75    55.00
5       78.00    83.25

In [50]:
exam.groupby('nclass').mean()[["math", 'english', 'science']]

         math  english  science
nclass
1       46.25    94.75    61.50
2       61.25    84.25    58.25
3       45.00    86.50    39.25
4       56.75    84.75    55.00
5       78.00    74.25    83.25

In [51]:
exam.groupby('nclass').agg(['mean', 'median'])

          id          math        english        science
        mean median   mean median    mean median    mean median
nclass
1        2.5    2.5  46.25   47.5   94.75   97.5   61.50   59.0
2        6.5    6.5  61.25   65.0   84.25   84.5   58.25   55.0
3       10.5   10.5  45.00   47.5   86.50   91.5   39.25   38.5
4       14.5   14.5  56.75   53.0   84.75   92.5   55.00   65.0
5       18.5   18.5  78.00   79.0   74.25   73.0   83.25   88.5

In [52]:
exam.groupby('nclass').agg('mean')['math']

nclass
1    46.25
2    61.25
3    45.00
4    56.75
5    78.00
Name: math, dtype: float64

In [53]:
exam.groupby('nclass').agg(mean_math = ('math', 'mean'))

        mean_math
nclass
1           46.25
2           61.25
3           45.00
4           56.75
5           78.00

In [54]:
exam.groupby('nclass').agg(mean_math = ('math', 'mean'),
                           mean_eng = ('english', 'mean'))

        mean_math  mean_eng
nclass
1           46.25     94.75
2           61.25     84.25
3           45.00     86.50
4           56.75     84.75
5           78.00     74.25

In [55]:
exam.groupby('nclass').agg({'math': 'mean', 'english': 'mean'})

         math  english
nclass
1       46.25    94.75
2       61.25    84.25
3       45.00    86.50
4       56.75    84.75
5       78.00    74.25

In [56]:
exam.groupby('nclass').agg({'math': ['mean', 'min', 'max']})

         math
         mean min max
nclass
1       46.25  30  60
2       61.25  25  90
3       45.00  20  65
4       56.75  46  75
5       78.00  65  89

In [57]:
exam.groupby('nclass').agg({'math': ['mean', 'min', 'max'], 'english': ['mean', 'median', 'max']})

         math         english
         mean min max    mean median max
nclass
1       46.25  30  60   94.75   97.5  98
2       61.25  25  90   84.25   84.5  90
3       45.00  20  65   86.50   91.5  98
4       56.75  46  75   84.75   92.5  98
5       78.00  65  89   74.25   73.0  83

In [62]:
exam.groupby('nclass', as_index=True).agg(mean_math = ('math', 'mean'))

        mean_math
nclass
1           46.25
2           61.25
3           45.00
4           56.75
5           78.00

In [63]:
exam.groupby('nclass', as_index=False).agg(mean_math = ('math', 'mean'))

   nclass  mean_math
0       1      46.25
1       2      61.25
2       3      45.00
3       4      56.75
4       5      78.00

## DataFrameGroupBy 알아보기

In [58]:
range(5)

range(0, 5)

In [59]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
list(exam.groupby('nclass') )

[(1,
     id  nclass  math  english  science
  0   1       1    50       98       50
  1   2       1    60       97       60
  2   3       1    45       86       78
  3   4       1    30       98       58),
 (2,
     id  nclass  math  english  science
  4   5       2    25       80       65
  5   6       2    50       89       98
  6   7       2    80       90       45
  7   8       2    90       78       25),
 (3,
      id  nclass  math  english  science
  8    9       3    20       98       15
  9   10       3    50       98       45
  10  11       3    65       65       65
  11  12       3    45       85       32),
 (4,
      id  nclass  math  english  science
  12  13       4    46       98       65
  13  14       4    48       87       12
  14  15       4    75       56       78
  15  16       4    58       98       65),
 (5,
      id  nclass  math  english  science
  16  17       5    65       68       98
  17  18       5    80       78       90
  18  19       5    89       68       87
  19  20       5    78       83       58)]

In [66]:
d = list(exam.groupby('nclass'))

In [67]:
d[1]

(2,
    id  nclass  math  english  science
 4   5       2    25       80       65
 5   6       2    50       89       98
 6   7       2    80       90       45
 7   8       2    90       78       25)

In [68]:
d[1][1]

   id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25

In [69]:
d[1][0]

2

In [70]:
for i in range(5):
  print(i, end=' ')

0 1 2 3 4

In [71]:
for d in exam.groupby('nclass'):
  print(d, end='\n ============== \n')

(1,    id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58)
 ==============
(2,    id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25)
 ==============
(3,     id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32)
 ==============
(4,     id  nclass  math  english  science
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65)
 ==============
(5,     id  nclass  math  english  science
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58)
 ==============

In [72]:
for n,df in exam.groupby('nclass'):
  print(n, '반')
  print(df, end='\n ============== \n')

1 반
   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
 ==============
2 반
   id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25
 ==============
3 반
    id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
 ==============
4 반
    id  nclass  math  english  science
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
 ==============
5 반
    id  nclass  math  english  science
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58
 ==============

In [75]:
for n,df in exam.groupby('nclass'):
  print(n, '반')
  print('데이터프레임', '\n')
  print(df, end = '\n' + '='*40 + '\n\n')

1 반
데이터프레임

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
========================================

2 반
데이터프레임

   id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25
========================================

3 반
데이터프레임

    id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
========================================

4 반
데이터프레임

    id  nclass  math  english  science
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
========================================

5 반
데이터프레임

    id  nclass  math  english  science
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58
========================================

In [76]:
exam.groupby('nclass').agg(mean_math   = ('math', 'mean'),
                           sum_math    = ('math', 'sum'),
                           median_math = ('math', 'median'),
                           count       = ('nclass', 'count'))

        mean_math  sum_math  median_math  count
nclass
1           46.25       185         47.5      4
2           61.25       245         65.0      4
3           45.00       180         47.5      4
4           56.75       227         53.0      4
5           78.00       312         79.0      4

In [77]:
exam.groupby('nclass').count()

        id  math  english  science
nclass
1        4     4        4        4
2        4     4        4        4
3        4     4        4        4
4        4     4        4        4
5        4     4        4        4

## mpg 데이터 활용 groupby() agg()

In [78]:
mpg = pd.read_csv('data/mpg.csv')
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   manufacturer  234 non-null    object
 1   model         234 non-null    object
 2   displ         234 non-null    float64
 3   year          234 non-null    int64
 4   cyl           234 non-null    int64
 5   trans         234 non-null    object
 6   drv           234 non-null    object
 7   cty           234 non-null    int64
 8   hwy           234 non-null    int64
 9   fl            234 non-null    object
 10  category      234 non-null    object
dtypes: float64(1), int64(4), object(6)
memory usage: 20.2+ KB

In [80]:
mpg.columns

Index(['manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty',
       'hwy', 'fl', 'category'],
      dtype='object')

In [81]:
mpg.sample(frac=.02)

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
153,nissan,pathfinder 4wd,5.6,2008,8,auto(s5),4,12,18,p,suv
202,toyota,toyota tacoma 4wd,2.7,2008,4,manual(m5),4,17,22,r,pickup
85,ford,f150 pickup 4wd,4.6,1999,8,manual(m5),4,13,16,r,pickup
199,toyota,land cruiser wagon 4wd,5.7,2008,8,auto(s6),4,13,18,r,suv
226,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact

In [82]:
mpg.groupby(['manufacturer', 'drv']).agg(mean_cty = ('cty', 'mean'))

                  mean_cty
manufacturer drv
audi         4       16.82
             f       18.86
chevrolet    4       12.50
             f       18.80
             r       14.10
dodge        4       12.00
             f       15.82
ford         4       13.31
             r       14.75
honda        f       24.44
hyundai      f       18.64
jeep         4       13.50
land rover   4       11.50
lincoln      r       11.33
mercury      4       13.25
nissan       4       13.75
             f       20.00
pontiac      f       17.00
subaru       4       19.29
toyota       4       14.93
             f       21.37
volkswagen   f       20.93

In [83]:
mpg.groupby(['drv', 'manufacturer']).agg(mean_cty = ('cty', 'mean'))

                  mean_cty
drv manufacturer
4   audi             16.82
    chevrolet        12.50
    dodge            12.00
    ford             13.31
    jeep             13.50
    land rover       11.50
    mercury          13.25
    nissan           13.75
    subaru           19.29
    toyota           14.93
f   audi             18.86
    chevrolet        18.80
    dodge            15.82
    honda            24.44
    hyundai          18.64
    nissan           20.00
    pontiac          17.00
    toyota           21.37
    volkswagen       20.93
r   chevrolet        14.10
    ford             14.75
    lincoln          11.33

In [84]:
mpg.groupby(['manufacturer', 'category']).agg(mean_cty = ('cty', 'mean'), mean_hwy = ('hwy', 'mean'))

                         mean_cty  mean_hwy
manufacturer category
audi         compact        17.93     26.93
             midsize        16.00     24.00
chevrolet    2seater        15.40     24.80
             midsize        18.80     27.60
             suv            12.67     17.11
dodge        minivan        15.82     22.36
             pickup         12.05     16.11
             suv            11.86     16.00
ford         pickup         13.00     16.43
             subcompact     15.89     23.22
             suv            12.89     17.78
honda        subcompact     24.44     32.56
hyundai      midsize        19.00     27.71
             subcompact     18.29     26.00
jeep         suv            13.50     17.62
land rover   suv            11.50     16.50
lincoln      suv            11.33     17.00
mercury      suv            13.25     18.00
nissan       compact        20.00     28.00
             midsize        20.00     27.43
             suv            13.75     18.00
pontiac      midsize        17.00     26.40
subaru       compact        19.75     26.00
             subcompact     19.50     26.00
             suv            18.83     25.00
toyota       compact        22.25     30.58
             midsize        19.86     28.29
             pickup         15.57     19.43
             suv            14.38     18.25
volkswagen   compact        20.79     28.50
             midsize        18.57     27.57
             subcompact     24.00     32.83

In [85]:
mpg.groupby(['category', 'manufacturer']).agg(mean_cty = ('cty', 'mean'), mean_hwy = ('hwy', 'mean'))

                         mean_cty  mean_hwy
category   manufacturer
2seater    chevrolet        15.40     24.80
compact    audi             17.93     26.93
           nissan           20.00     28.00
           subaru           19.75     26.00
           toyota           22.25     30.58
           volkswagen       20.79     28.50
midsize    audi             16.00     24.00
           chevrolet        18.80     27.60
           hyundai          19.00     27.71
           nissan           20.00     27.43
           pontiac          17.00     26.40
           toyota           19.86     28.29
           volkswagen       18.57     27.57
minivan    dodge            15.82     22.36
pickup     dodge            12.05     16.11
           ford             13.00     16.43
           toyota           15.57     19.43
subcompact ford             15.89     23.22
           honda            24.44     32.56
           hyundai          18.29     26.00
           subaru           19.50     26.00
           volkswagen       24.00     32.83
suv        chevrolet        12.67     17.11
           dodge            11.86     16.00
           ford             12.89     17.78
           jeep             13.50     17.62
           land rover       11.50     16.50
           lincoln          11.33     17.00
           mercury          13.25     18.00
           nissan           13.75     18.00
           subaru           18.83     25.00
           toyota           14.38     18.25

In [86]:
mpg.query('manufacturer == "audi"').groupby(['drv']).agg(n = ('drv', 'count'))

      n
drv
4    11
f     7

In [89]:
mpg.query('manufacturer == "honda"').groupby(['drv']).agg(n = ('drv', 'count'))

     n
drv
f    9

In [90]:
mpg.query('manufacturer == "chevrolet"').groupby(['drv']).agg(n = ('drv', 'count'))

      n
drv
4     4
f     5
r    10

In [91]:
mpg.query('manufacturer == "chevrolet"') \
   .groupby(['drv']) \
   .agg(n = ('drv', 'count'))

      n
drv
4     4
f     5
r    10

In [92]:
mpg.query('manufacturer == "chevrolet"').groupby(['drv']).count()

     manufacturer  model  displ  year  cyl  trans  cty  hwy  fl  category
drv
4               4      4      4     4    4      4    4    4   4         4
f               5      5      5     5    5      5    5    5   5         5
r              10     10     10    10   10     10   10   10  10        10

In [93]:
mpg.query('manufacturer == "chevrolet"').groupby(['drv']).count()[["model"]]

     model
drv
4        4
f        5
r       10

In [94]:
mpg.query('manufacturer == "chevrolet"').groupby(['drv']) \
   .count()[["model"]].rename(columns={'model': 'n'})

      n
drv
4     4
f     5
r    10

In [95]:
mpg.groupby('drv').agg(n = ('drv', 'count'))

       n
drv
4    103
f    106
r     25

In [96]:
mpg[['drv', 'cyl']].value_counts()

drv  cyl
f    4      58
4    8      48
f    6      43
4    6      32
     4      23
r    8      21
f    5       4
r    6       4
f    8       1
Name: count, dtype: int64

In [97]:
mpg.groupby(['drv', 'cyl']).agg('count')[['model']]

         model
drv cyl
4   4       23
    6       32
    8       48
f   4       58
    5        4
    6       43
    8        1
r   6        4
    8       21

In [98]:
mpg[['drv', 'cyl']].value_counts().to_frame()

         count
drv cyl
f   4       58
4   8       48
f   6       43
4   6       32
    4       23
r   8       21
f   5        4
r   6        4
f   8        1

In [99]:
mpg[['drv', 'cyl']].value_counts().to_frame().query('count > 40')

         count
drv cyl
f   4       58
4   8       48
f   6       43

In [100]:
mpg['drv'].value_counts().to_frame()

     count
drv
f      106
4      103
r       25

In [101]:
mpg['drv'].value_counts().to_frame('n')

       n
drv
f    106
4    103
r     25

In [102]:
mpg['drv'].value_counts().to_frame('n').rename_axis('drive')

         n
drive
f      106
4      103
r       25

In [103]:
mpg.groupby('drv').agg(n = ('drv', 'count'))

       n
drv
4    103
f    106
r     25

In [104]:
mpg.groupby('drv').agg(n = ('drv', 'count')).query('n > 100')

       n
drv
4    103
f    106

In [105]:
mpg.query('category == "suv"') \
   .assign(total = (mpg.hwy + mpg.cty) / 2) \
   .groupby('manufacturer') \
   .agg(mean_total = ('total', 'mean')) \
   .sort_values('mean_total', ascending=False) \
   .head(5)

              mean_total
manufacturer
subaru             21.92
toyota             16.31
nissan             15.88
mercury            15.62
jeep               15.56

In [106]:
mpg.groupby('manufacturer')

In [107]:
mpg.groupby(['manufacturer'])

In [108]:
mpg.groupby('manufacturer').count()

              model  displ  year  cyl  trans  drv  cty  hwy  fl  category
manufacturer
audi             18     18    18   18     18   18   18   18  18        18
chevrolet        19     19    19   19     19   19   19   19  19        19
dodge            37     37    37   37     37   37   37   37  37        37
ford             25     25    25   25     25   25   25   25  25        25
honda             9      9     9    9      9    9    9    9   9         9
hyundai          14     14    14   14     14   14   14   14  14        14
jeep              8      8     8    8      8    8    8    8   8         8
land rover        4      4     4    4      4    4    4    4   4         4
lincoln           3      3     3    3      3    3    3    3   3         3
mercury           4      4     4    4      4    4    4    4   4         4
nissan           13     13    13   13     13   13   13   13  13        13
pontiac           5      5     5    5      5    5    5    5   5         5
subaru           14     14    14   14     14   14   14   14  14        14
toyota           34     34    34   34     34   34   34   34  34        34
volkswagen       27     27    27   27     27   27   27   27  27        27

In [109]:
mpg.groupby(['manufacturer']).count()

              model  displ  year  cyl  trans  drv  cty  hwy  fl  category
manufacturer
audi             18     18    18   18     18   18   18   18  18        18
chevrolet        19     19    19   19     19   19   19   19  19        19
dodge            37     37    37   37     37   37   37   37  37        37
ford             25     25    25   25     25   25   25   25  25        25
honda             9      9     9    9      9    9    9    9   9         9
hyundai          14     14    14   14     14   14   14   14  14        14
jeep              8      8     8    8      8    8    8    8   8         8
land rover        4      4     4    4      4    4    4    4   4         4
lincoln           3      3     3    3      3    3    3    3   3         3
mercury           4      4     4    4      4    4    4    4   4         4
nissan           13     13    13   13     13   13   13   13  13        13
pontiac           5      5     5    5      5    5    5    5   5         5
subaru           14     14    14   14     14   14   14   14  14        14
toyota           34     34    34   34     34   34   34   34  34        34
volkswagen       27     27    27   27     27   27   27   27  27        27

## 데이터 합치기

In [110]:
test1 = pd.DataFrame({'id'      : [1, 2, 3, 4, 5],
                      'midterm' : [60, 80, 70, 90, 85]})

test2 = pd.DataFrame({'id'    : [1, 2, 3, 4, 5],
                      'final' : [70, 83, 65, 95, 80]})

In [111]:
test1

   id  midterm
0   1       60
1   2       80
2   3       70
3   4       90
4   5       85

In [112]:
test2

   id  final
0   1     70
1   2     83
2   3     65
3   4     95
4   5     80

In [113]:
pd.merge(test1, test2)

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [114]:
pd.merge(test1, test2, on = 'id')

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [115]:
pd.merge(test1, test2, on = 'id', how='inner')

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [116]:
test1.merge(test2, on = 'id', how='inner')

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [117]:
test2.merge(test1, on = 'id', how='inner')

   id  final  midterm
0   1     70       60
1   2     83       80
2   3     65       70
3   4     95       90
4   5     80       85

In [118]:
name = pd.DataFrame({'nclass'  : [1, 2, 3, 4, 5],
                     'teacher' : ['kim', 'lee', 'park', 'choi', 'jung']})
name

   nclass teacher
0       1     kim
1       2     lee
2       3    park
3       4    choi
4       5    jung

In [119]:
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [120]:
pd.merge(exam, name)

    id  nclass  math  english  science teacher
0    1       1    50       98       50     kim
1    2       1    60       97       60     kim
2    3       1    45       86       78     kim
3    4       1    30       98       58     kim
4    5       2    25       80       65     lee
5    6       2    50       89       98     lee
6    7       2    80       90       45     lee
7    8       2    90       78       25     lee
8    9       3    20       98       15    park
9   10       3    50       98       45    park
10  11       3    65       65       65    park
11  12       3    45       85       32    park
12  13       4    46       98       65    choi
13  14       4    48       87       12    choi
14  15       4    75       56       78    choi
15  16       4    58       98       65    choi
16  17       5    65       68       98    jung
17  18       5    80       78       90    jung
18  19       5    89       68       87    jung
19  20       5    78       83       58    jung

In [121]:
pd.merge(exam, name, on = 'nclass', how='inner')

    id  nclass  math  english  science teacher
0    1       1    50       98       50     kim
1    2       1    60       97       60     kim
2    3       1    45       86       78     kim
3    4       1    30       98       58     kim
4    5       2    25       80       65     lee
5    6       2    50       89       98     lee
6    7       2    80       90       45     lee
7    8       2    90       78       25     lee
8    9       3    20       98       15    park
9   10       3    50       98       45    park
10  11       3    65       65       65    park
11  12       3    45       85       32    park
12  13       4    46       98       65    choi
13  14       4    48       87       12    choi
14  15       4    75       56       78    choi
15  16       4    58       98       65    choi
16  17       5    65       68       98    jung
17  18       5    80       78       90    jung
18  19       5    89       68       87    jung
19  20       5    78       83       58    jung

In [122]:
group_a = pd.DataFrame({'id'   : [1, 2, 3, 4, 5],
                        'test' : [60, 80, 70, 90, 85]})

group_b = pd.DataFrame({'id'   : [6, 7, 8, 9, 10],
                        'test' : [70, 83, 65, 95, 80]})

In [123]:
group_a

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85

In [124]:
group_b

   id  test
0   6    70
1   7    83
2   8    65
3   9    95
4  10    80

In [125]:
pd.concat([group_a, group_b])

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85
0   6    70
1   7    83
2   8    65
3   9    95
4  10    80

In [126]:
pd.concat([group_a, group_b]).reset_index()

   index  id  test
0      0   1    60
1      1   2    80
2      2   3    70
3      3   4    90
4      4   5    85
5      0   6    70
6      1   7    83
7      2   8    65
8      3   9    95
9      4  10    80

In [127]:
pd.concat([group_a, group_b]).reset_index(drop=True)

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85
5   6    70
6   7    83
7   8    65
8   9    95
9  10    80

## merge() 중간고사 예상 문제

In [129]:
df1 = pd.DataFrame([[1, 'apple'], [2, 'banana']],
                  columns = ['id', 'fruits'])
df1

   id  fruits
0   1   apple
1   2  banana

In [130]:
df2 = pd.DataFrame([[1, 3000], [5, 500]],
                  columns = ['id', 'price'])
df2

   id  price
0   1   3000
1   5    500

In [131]:
pd.merge(df1, df2)

   id fruits  price
0   1  apple   3000

In [132]:
pd.merge(df1, df2, on = 'id', how='left')

   id  fruits   price
0   1   apple  3000.0
1   2  banana     NaN

In [133]:
df2

   id  price
0   1   3000
1   5    500

In [134]:
pd.merge(df1, df2, on = 'id', how='right')

   id fruits  price
0   1  apple   3000
1   5    NaN    500

In [135]:
df1

   id  fruits
0   1   apple
1   2  banana

In [136]:
pd.merge(df1, df2, how='cross')

   id_x  fruits  id_y  price
0     1   apple     1   3000
1     1   apple     5    500
2     2  banana     1   3000
3     2  banana     5    500

In [137]:
df1.merge(df2, how='cross')

   id_x  fruits  id_y  price
0     1   apple     1   3000
1     1   apple     5    500
2     2  banana     1   3000
3     2  banana     5    500

## 단원 06 종료